pool:
  vmImage: 'vs2017-win2016'
steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
- task: CredScan@2
  inputs:
    toolMajorVersion: 'V2'
- task: Semmle@1
  displayName: 'Run Semmle (python)'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken) 
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)'
    language: 'python'
    querySuite: 'Recommended'
    timeout: '1800'
    ram: '16384'
    addProjectDirToScanningExclusionList: true
